# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: test-suite

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        gemfile: ["rails-7.0.x"]
        ruby: [3.2]
        include:
          - gemfile: rails-7.0.x
            ruby: '3.1'
          - gemfile: rails-7.0.x
            ruby: '3.0'
          - gemfile: rails-7.0.x
            ruby: '2.7'
          - gemfile: rails-6.1.x
            ruby: '3.1'
          - gemfile: rails-6.1.x
            ruby: '3.0'
          - gemfile: rails-6.1.x
            ruby: 2.7
          - gemfile: rails-6.0.x
            ruby: 2.7
          - gemfile: rails-5.2.x
            ruby: 2.7

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/Gemfile.${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rspec
